### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ddlidded** [shihjay2/nosh3#6]
The message bad gateway is appearing when going to my server-pointed domain name even though the setup in the terminal yielded a success message. 

Ubuntu 20.04.5 LTS
<img width="366" alt="Screenshot 2023-03-08 at 3 21 54 AM" src="https://user-images.githubusercontent.com/63270906/223700698-7cae2f1c-3ead-43d4-bd0b-04918eceffbd.png">

<img width="1492" alt="Screenshot 2023-03-08 at 3 22 30 AM" src="https://user-images.githubusercontent.com/63270906/223700745-271c8e4b-9739-48c2-977e-8a49923a2130.png">

**Comment by shihjay2** [comment]
It may help if you could post the results of these commands in your server.
```
docker logs $(docker ps -aqf "name=^nosh$") -f
```
```
docker logs $(docker ps -aqf "name=^router$") -f
```
```
docker logs $(docker ps -aqf "name=^couchdb$") -f
```

**Comment by hammercuba** [comment]
Hi, same issue here, the log:
root@srv1:~/nosh3# docker logs $(docker ps -aqf "name=^router$") -f
time="2024-01-17T00:03:16Z" level=info msg="Configuration loaded from flags."
time="2024-01-17T00:06:25Z" level=error msg="service \"nosh\" error: unable to find the IP address for the container \"/nosh\": the server is ignored" container=nosh-nosh3-08c9a9ec3f585a28b10690bafbcf85a1e6e5a31c37c7c538e853e41108c7014a providerName=docker

**Comment by shihjay2** [comment]
@hammercuba can you post the log for the nosh container?
```
docker logs $(docker ps -aqf "name=^nosh$") -f
```
The nosh container is likely not loading hence the absence of an IP address...

**Comment by hammercuba** [comment]
root@srv1:~/nosh3# docker logs $(docker ps -aqf "name=^nosh$") -f
listening on 4000
GET /start - - - - ms
GET / 404 139 - 11.190 ms
GET / 404 139 - 3.239 ms

/usr/src/app/node_modules/node-fetch/lib/index.js:1491
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://db.#######.duckdns.org/_users/ failed, reason: connect ETIMEDOUT **.**.**.**:443
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

Node.js v19.9.0
listening on 4000
GET /start - - - - ms

/usr/src/app/node_modules/node-fetch/lib/index.js:1491
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://db.####.duckdns.org/_users/ failed, reason: connect ETIMEDOUT **.**.***.**:443
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

Node.js v19.9.0
listening on 4000
GET /robots.txt 404 149 - 22.641 ms
GET / 404 139 - 7.010 ms
GET / 404 139 - 2.052 ms
GET / 404 139 - 1.972 ms
GET /favicon.ico 404 150 - 2.096 ms

**Comment by hammercuba** [comment]
the host is a Debian 12 just with docker, under a at&t fiber, with the port redirection 80 and 443, and duckdns.org  configured

**Comment by shihjay2** [comment]
What is the COUCHDB_URL value in the .env file?  I'm assuming it's db.####.duckdns.org based on your logs.  Can you confirm that db.####.duckdns.org is reachable (ie CNAME is registered for that subdomain).

**Comment by hammercuba** [comment]
Yes, is reachable

**Comment by hammercuba** [comment]
this is from a linode server 

root@srv8:~# nslookup db.####.duckdns.org
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   db.####.duckdns.org
Address: ##.##.##.##

root@srv8:~# telnet db.#####.duckdns.org 443
Trying ##.##.##.##...
Connected to db.####.duckdns.org.
Escape character is '^]'.
get
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad RequestConnection closed by foreign host.
root@srv8:~#

**Comment by shihjay2** [comment]
Can you check if https://db.####.duckdns.org/_utils/#login is accessible via browser.  If so, I have made some updates in the commit [cae56c3](https://github.com/shihjay2/nosh3/commit/cae56c390d1ab359a67c50e2e0e9182b581bebd1)

**Comment by hammercuba** [comment]
![Screen Shot 2024-01-16 at 10 23 18 PM](https://github.com/shihjay2/nosh3/assets/79805329/ca3b7a3f-b8b1-4aa3-b62c-701bd1b53ba9)

**Comment by hammercuba** [comment]
I did a fresh reinstall of everything and it's doing the same, what can I do?

**Comment by shihjay2** [comment]
@hammercuba can you post the log for the nosh container again as the recent updates should not throw the same type of errors previously shared.

**Comment by hammercuba** [comment]
I do a docker-compose down -v, then erase all the nosh3 folder and proceed to run the script again, same logs.

**Comment by hammercuba** [comment]
/usr/src/app/node_modules/node-fetch/lib/index.js:1491
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://db.******.duckdns.org/keys/ failed, reason: connect ETIMEDOUT *******:443
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

**Comment by shihjay2** [comment]
Looks like a different error - if you used the docker-compose install method in the readme, it should automatically update the docker image (built a few minutes ago) based on the latest commit [97e0368](https://github.com/shihjay2/nosh3/commit/97e0368e33a2de91f6859ae43bb6348019b76a0f)

**Comment by hammercuba** [comment]
database is empty, and connection takes forever until stop trying, open all the ports in the firewall to see if something changes but did't work, any idea?

**Comment by shihjay2** [comment]
Were you able to start up the most recent docker image for NOSH and if so, can you present the logs again?

**Comment by hammercuba** [comment]
root@docker-srv:~# docker logs $(docker ps -aqf "name=^nosh$") -f      
listening on 4000
GET /start/ 200 20 - 129493.282 ms
GET /start/ 200 20 - 130320.358 ms
GET /robots.txt 404 149 - 3.930 ms
GET / 404 139 - 1.861 ms
GET / 404 139 - 0.433 ms
GET / 404 139 - 1.361 ms
---------------------------------------------
couchdb
[notice] 2024-01-18T22:00:05.089621Z nonode@nohost <0.366.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
[error] 2024-01-18T22:00:05.090147Z nonode@nohost emulator -------- Error in process <0.9150.1> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,[<<"_users">>],[{file,"src/mem3_shards.erl"},{line,430}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,405}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,434}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,100}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,214}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,160}]}]}

[error] 2024-01-18T22:00:05.090320Z nonode@nohost emulator -------- Error in process <0.9150.1> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,[<<"_users">>],[{file,"src/mem3_shards.erl"},{line,430}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,405}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,434}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,100}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,214}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,160}]}]}

[notice] 2024-01-18T22:00:10.090603Z nonode@nohost <0.366.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
[error] 2024-01-18T22:00:10.091212Z nonode@nohost emulator -------- Error in process <0.9199.1> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,[<<"_users">>],[{file,"src/mem3_shards.erl"},{line,430}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,405}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,434}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,100}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,214}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,160}]}]}

[error] 2024-01-18T22:00:10.091523Z nonode@nohost emulator -------- Error in process <0.9199.1> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,[<<"_users">>],[{file,"src/mem3_shards.erl"},{line,430}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,405}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,434}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,100}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,214}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,160}]}]}

[notice] 2024-01-18T22:00:15.091622Z nonode@nohost <0.366.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
[error] 2024-01-18T22:00:15.092111Z nonode@nohost emulator -------- Error in process <0.9232.1> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,[<<"_users">>],[{file,"src/mem3_shards.erl"},{line,430}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,405}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,434}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,100}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,214}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,160}]}]}

[error] 2024-01-18T22:00:15.092368Z nonode@nohost emulator -------- Error in process <0.9232.1> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,[<<"_users">>],[{file,"src/mem3_shards.erl"},{line,430}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,405}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,434}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,100}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,214}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,160}]}]}

[notice] 2024-01-18T22:00:20.092620Z nonode@nohost <0.366.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
[error] 2024-01-18T22:00:20.093243Z nonode@nohost emulator -------- Error in process <0.9281.1> with exit value:


------------------------------
root@docker-srv:~# docker logs $(docker ps -aqf "name=^router$") -f  
time="2024-01-18T19:57:34Z" level=info msg="Configuration loaded from flags."
^C
root@docker-srv:~# 
![Screen Shot 2024-01-18 at 4 10 16 PM](https://github.com/shihjay2/nosh3/assets/79805329/a0c2186e-e682-4016-9ac6-a2c6c08ba7c0)

**Comment by shihjay2** [comment]
Thank you, I think for some reason (cannot replicate), your couchdb Docker instance isn't getting set up as a single_node (instead of cluster) and it's looking for the _users database but it stalls even though in my code there are CURL calls between NOSH and couchdb to set that up for you when running /start.  I'm going to try a different approach, but this will be a future commit because I'm going to manually create a docker.ini file in the install routine to force couchdb to be single instance.  I'll let you know when it's ready.

**Comment by shihjay2** [comment]
If you want, you can do this yourself now and see if this works.  In the dbconf folder located in the root of the Docker folder for nosh, create a file named "docker.ini".  Inside the file should be:
```
[couchdb]
single_node=true
users_db_security_editable = true
```
Then do a `docker compose down;docker compose up -d` and see if the error persists.

**Comment by hammercuba** [comment]
root@docker-srv:~/nosh3# docker logs $(docker ps -aqf "name=^couchdb$") -f                
[info] 2024-01-19T00:13:10.375661Z nonode@nohost <0.248.0> -------- Preflight check: Checking For Monsters

[info] 2024-01-19T00:13:10.376982Z nonode@nohost <0.248.0> -------- Preflight check: Asserting Admin Account

[info] 2024-01-19T00:13:10.380079Z nonode@nohost <0.248.0> -------- Apache CouchDB 3.3.3 is starting.

[info] 2024-01-19T00:13:10.380167Z nonode@nohost <0.249.0> -------- Starting couch_sup
[info] 2024-01-19T00:13:10.423959Z nonode@nohost <0.248.0> -------- Apache CouchDB has started. Time to relax.

[notice] 2024-01-19T00:13:10.432878Z nonode@nohost <0.299.0> -------- rexi_server : started servers
[notice] 2024-01-19T00:13:10.434396Z nonode@nohost <0.303.0> -------- rexi_buffer : started servers
[notice] 2024-01-19T00:13:10.496756Z nonode@nohost <0.334.0> -------- mem3_reshard_dbdoc start init()
[notice] 2024-01-19T00:13:10.500899Z nonode@nohost <0.336.0> -------- mem3_reshard start init()
[notice] 2024-01-19T00:13:10.500965Z nonode@nohost <0.337.0> -------- mem3_reshard db monitor <0.337.0> starting
[notice] 2024-01-19T00:13:10.503551Z nonode@nohost <0.336.0> -------- mem3_reshard starting reloading jobs
[notice] 2024-01-19T00:13:10.503596Z nonode@nohost <0.336.0> -------- mem3_reshard finished reloading jobs
[info] 2024-01-19T00:13:10.541150Z nonode@nohost <0.343.0> -------- Apache CouchDB has started. Time to relax.

[info] 2024-01-19T00:13:10.541248Z nonode@nohost <0.343.0> -------- Apache CouchDB has started on http://any:5984/
[notice] 2024-01-19T00:13:10.606941Z nonode@nohost <0.433.0> -------- All system databases exist.
[notice] 2024-01-19T00:13:15.564598Z nonode@nohost <0.395.0> -------- couch_replicator_clustering : cluster stable
[notice] 2024-01-19T00:13:15.572560Z nonode@nohost <0.417.0> -------- Started replicator db changes listener <0.548.0>
[info] 2024-01-19T00:13:15.573950Z nonode@nohost <0.550.0> -------- open_result error {not_found,no_db_file} for _replicator
[notice] 2024-01-19T00:13:25.433474Z nonode@nohost <0.299.0> -------- rexi_server : cluster stable
[notice] 2024-01-19T00:13:25.433543Z nonode@nohost <0.303.0> -------- rexi_buffer : cluster stable

**Comment by hammercuba** [comment]
also, /start doesn't work, but /app/login take me to the login page

**Comment by shihjay2** [comment]
What is your .env value for NOSH_ROLE and INSTANCE?  /start would show a response of 'Invalid URL for this instance' if set to 'patient' and 'digitalocean' and may throw an error with 'patient' and other values for instance (not supported yet).

**Comment by hammercuba** [comment]
root@docker-srv:~/nosh3# cat .env 
MAGIC_API_KEY=pk_live_aaaaaaaaaaaaaa
MAILGUN_API_KEY=
SENDGRID_API_KEY=
MAILGUN_DOMAIN=
COUCHDB_URL=https://db.********.duckdns.org
COUCHDB_USER=admin
COUCHDB_PASSWORD=*******
COUCHDB_ENCRYPT_PIN=1234
INSTANCE=docker
# either [docker, digitalocean, local]
TRUSTEE_URL=
NOSH_DISPLAY=*******
NOSH_EMAIL=info@******.com
NOSH_DID=
NOSH_ROLE=provider
# either [patient, provider]
AUTH=magic
# either [magic, trustee]
USPSTF_KEY=
UMLS_KEY=
OIDC_RELAY_URL=
root@docker-srv:~/nosh3#

**Comment by shihjay2** [comment]
At this moment the /start call is broken until I update the code since I think some of the updates by adding the docker.ini is duplicative or not working (to initialize couchdb as a single node).  For now, you can just use /app/login (which is what happens if /start is able to determine that couchdb is correctly set up).

**Comment by shihjay2** [comment]
Updated docker image with commit [bad41e0](https://github.com/shihjay2/nosh3/commit/bad41e022673c70cf1f67a30871b0c23ea5691b8) which updated the /start code.

**Comment by hammercuba** [comment]
now when I try to log in said:
Error connecting to magic, please try again later

magic account setup as recommended

**Comment by shihjay2** [comment]
Unable to replicate - probably Magic servers were temporarily down at time of test; just checked now and I was successful in authentication.

**Comment by hammercuba** [comment]
![Screen Shot 2024-01-18 at 9 31 48 PM](https://github.com/shihjay2/nosh3/assets/79805329/1e5f7b59-d692-4a71-b1b0-564cc9da0b86)

**Comment by hammercuba** [comment]
oot@docker-srv:~/nosh3# docker logs $(docker ps -aqf "name=^nosh$") -f   
listening on 4000
GET /app/login 200 1551 - 8.684 ms
GET /app/js/chunk-vendors.864a8eb3.js 200 3456434 - 2.864 ms
GET /auth/config 200 85 - 5.014 ms
GET /app/service-worker.js 200 8231 - 2.625 ms
GET /app/workbox-5b385ed2.js 200 14450 - 2.442 ms
GET /app/index.html 200 1551 - 4.080 ms
GET /app/login 200 1551 - 2.483 ms
GET /app/js/chunk-vendors.864a8eb3.js 200 3456434 - 1.893 ms
GET /auth/config 200 85 - 1.917 ms
GET /app/service-worker.js 200 8231 - 1.790 ms
GET /app/workbox-5b385ed2.js 200 14450 - 1.132 ms
GET /app/dashboard 200 1551 - 7.140 ms
GET /app/js/chunk-vendors.864a8eb3.js 200 3456434 - 2.361 ms
GET /auth/config 200 85 - 1.535 ms
GET /app/service-worker.js 200 8231 - 2.428 ms
GET /app/workbox-5b385ed2.js 200 14450 - 1.843 ms
GET /start/ 200 20 - 131074.102 ms

**Comment by shihjay2** [comment]
Confirm if Magic API key is correct; log in to https://magic.link to confirm and check to see if you enabled an Allow list (recommended but not required, if set, make sure your NOSH domain is in the whitelist), etc...

**Comment by shihjay2** [comment]
Once the docker image is rebuilt from commit [158bb90](https://github.com/shihjay2/nosh3/commit/158bb9041e3e69049a43dcf50c9cfddea5567e8b), you can try again and look at the console log in the browser for any errors when using Magic to help you troubleshoot.

**Comment by hammercuba** [comment]
Cannot GET /auth/authenticate

**Comment by shihjay2** [comment]
The route /auth/authenticate is only POST, not GET - not sure where you're getting that error on the console log.

**Comment by hammercuba** [comment]
[Error] Failed to load resource: the server responded with a status of 502 () (authenticate, line 0)
[Log] r {message: "Request failed with status code 502", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: Object, request: XMLHttpRequest, …} (app.eeea16f9.js, line 1)

**Comment by shihjay2** [comment]
Have you used the /start path?  This was supposed to be fixed in the last commit; if you did not do that, there may be missing database tables that are throwing the error.

**Comment by hammercuba** [comment]
yep, with /start I just receive a "error with info call" msg, and no login

**Comment by shihjay2** [comment]
Can you share the output of `docker image ls` (I want to confirm if your Docker image has been updated)

**Comment by hammercuba** [comment]
root@docker-srv:~/nosh3# docker image ls
REPOSITORY              TAG       IMAGE ID       CREATED        SIZE
shihjay2/nosh3          latest    11c9961471d9   15 hours ago   254MB
shihjay2/nosh3          <none>    501c537d5b6c   20 hours ago   254MB
shihjay2/nosh3          <none>    477eaeada1b6   45 hours ago   254MB
couchdb                 <none>    07ba54687bbd   8 days ago     204MB
traefik                 latest    64586c703ab1   6 weeks ago    153MB
couchdb                 latest    d9602933014c   6 weeks ago    201MB
containrrr/watchtower   latest    e7dd50d07b86   2 months ago   14.7MB

**Comment by shihjay2** [comment]
Can you post the log for the nosh container again and show the screen for Fauxton when you login to the couchdb container (I want to see what database tables are set up).

**Comment by hammercuba** [comment]
root@docker-srv:~/nosh3# docker logs $(docker ps -aqf "name=^nosh$") -f   
listening on 4000
GET / 404 139 - 12.546 ms
GET / 404 139 - 4.552 ms
GET /start - - - - ms
GET /start 304 - - 130275.019 ms
GET /start 304 - - 131212.205 ms

**Comment by hammercuba** [comment]
![Screen Shot 2024-01-19 at 3 01 53 PM](https://github.com/shihjay2/nosh3/assets/79805329/942661e2-5ed6-4ecf-8dee-80cedbdb53f8)

**Comment by shihjay2** [comment]
I updated the code to show more verbose error responses for \start in commit [889eba4](https://github.com/shihjay2/nosh3/commit/889eba4868d505355ecc9e900131e1d5b3f88153).  Docker image should have been updated by now.

**Comment by hammercuba** [comment]
{"message":"error with info call","error":{"message":"request to https://db.######.duckdns.org/users/ failed, reason: connect ETIMEDOUT #.#.#.#:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"}}

**Comment by shihjay2** [comment]
Add these lines to docker.ini in dbconfig.  
```
[httpd]
enable_cors = true

[cors]
origins = *
credentials = true
methods = GET, PUT, POST, HEAD, DELETE
headers = accept, authorization, content-type, origin, referer

[chttpd]
authentication_handlers = {chttpd_auth, cookie_authentication_handler}, {chttpd_auth, jwt_authentication_handler}, {chttpd_auth, default_authentication_handler}
```
Then do `docker compose down;docker compose up -d` again.

I have made changes to the code in commit [12d87d4](https://github.com/shihjay2/nosh3/commit/12d87d4fc8a736a342df7c92373911edc63cfad7) and the docker image is being rebuilt again.

**Comment by hammercuba** [comment]
ok, tried everything, can you please provide me the environment you use so I can replicate? thanks in advance

**Comment by hammercuba** [comment]
@shihjay2 any help?

**Comment by shihjay2** [comment]
@hammercuba I have tested the most recent commit and docker image on both Digitalocean Droplets with Ubuntu Server (22.10) and on a KVM on bare metal Ubuntu Server 23.10 (bare install) - using the Easy Installation in the readme:
```
sudo wget -qO do-install.sh https://raw.githubusercontent.com/shihjay2/nosh3/main/do-install.sh && sudo chmod +x do-install.sh && sudo bash do-install.sh
```
I was able to login using Magic with no errors.

**Comment by hammercuba** [comment]
fresh install, everything go ok but i can't connect via /start, also a lot of request with 200, [notice] 2024-01-28T14:40:41.153360Z nonode@nohost <0.879.0> 0839d51b34 db.clinigjh.duckdns.org 15.204.248.55 undefined GET / 200 ok 22
[notice] 2024-01-28T14:40:46.533722Z nonode@nohost <0.879.0> 73526efcc1 db.clinicbvj.duckdns.org 51.81.245.138 undefined GET / 200 ok 0
[notice] 2024-01-28T14:40:53.391410Z nonode@nohost <0.879.0> f575ad0564 db.clinicjhgj.duckdns.org 51.81.245.138 undefined GET /favicon.ico 404 ok 0
[notice] 2024-01-28T14:41:11.131331Z nonode@nohost <0.879.0> 1e4e530c9e db.clinihgh.duckdns.org 205.169.39.241 undefined GET / 200 ok 0
[notice] 2024-01-28T14:42:54.712976Z nonode@nohost <0.1963.0> e30f04e769 db.clinicjhgj.duckdns.org 45.130.83.29 undefined GET / 200 ok 0
[notice] 2024-01-28T14:42:55.550786Z nonode@nohost <0.1963.0> 1684d06357 db.clinicjhgj.duckdns.org 45.130.83.11 undefined GET / 200 ok 0
[notice] 2024-01-28T14:42:57.280319Z nonode@nohost <0.1963.0> 3f22e198bc db.clinicjhgj.duckdns.org 45.92.229.154 undefined GET / 200 ok 0
[notice] 2024-01-28T14:42:57.874948Z nonode@nohost <0.1963.0> 5bf93384eb db.clinicjhgj.duckdns.org 45.130.83.25 undefined GET / 200 ok 0
[notice] 2024-01-28T14:43:05.060172Z nonode@nohost <0.1963.0> 2cf5c0b736 db.clinijhj.duckdns.org 45.92.229.157 undefined GET / 200 ok 0
[notice] 2024-01-28T14:43:05.344243Z nonode@nohost <0.1963.0> 04a89d7db4 db.clinijhgj
![Screen Shot 2024-01-28 at 8 47 57 AM](https://github.com/shihjay2/nosh3/assets/79805329/c163c800-a626-470c-8dd0-be9fc008a631)
.duckdns.org 45.130.83.9 undefined GET / 200 ok 0

how is this possible if the VM is Just started ?

**Comment by shihjay2** [comment]
Is there another reverse proxy or firewall that exists between your VM and WAN?   It sounds like you have loopback causing these undefined GET requests.  Does your browser show a SSL cert successfully installed?  If not, that could be the issue.   The default behavior is that Traffic (the virtual router and reverse proxy) that puts all the Docker containers together also generates SSL cert for the DNS domain and subdomains through Let's Encrypt and it might by its doing an HTTP challenge before granting the cert but it's not going through.
