### ISSUE TITLE
Stuck at "Verifying User" login screen

### ISSUE THREAD

**Issue by christian-geier** [shihjay2/nosh3#9]
After installing NOSH3 and using the /start link and confirming the token, I am stuck at the following login screen
![image](https://github.com/shihjay2/nosh3/assets/7210438/5d18a299-6ed9-4532-81a5-56d1192ed74d)

It seems to be a http/https access issue with the DB but unsure how to fix this

registerServiceWorker.js:8 App is being served from cache by a service worker.
For more details, visit https://goo.gl/AFskqB
registerServiceWorker.js:14 Service worker has been registered.
index.es.js:3013 Mixed Content: The page at 'https://noshdemo.com/app/login' was loaded over HTTPS, but requested an insecure resource 'http://couchdb:5984/users/'. This request has been blocked; the content must be served over HTTPS.
Tt.fetch @ index.es.js:3013
index.es.js:3013     Uncaught (in promise) TypeError: Failed to fetch
    at Tt.fetch (index.es.js:3013:10)
    at fetch (LoginView.vue:286:26)
    at s (index.es.js:6829:12)
    at c (index.es.js:6857:12)
    at u (index.es.js:6905:20)
    at n.fetch (index.es.js:7078:12)
    at vt (index-browser.es.js:172:6)
    at It (index-browser.es.js:197:3)
    at Tt.<anonymous> (index-browser.es.js:1552:3)
    at index-browser.es.js:139:21
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by christian-geier** [comment]
Changing COUCHDB_URL=http://couchdb:5984 to COUCHDB_URL=https://db.noshdemo.com in the .env file fixed the login issue
